export interface Comic {
  id: number;
  title: string;
  issueNumber?: string;
  description: string;
  coverImageUrl: string;
  releaseDate?: string; // e.g., '2023-10-26'
  creators: {
    writer: string[];
    artist: string[];
    coverArtist?: string[];
  };
  featuredCharacters: { id: number; name: string }[];
  genres?: string[];
  downloadLinks?: Record<string, string>;
  additionalInfo?: Record<string, string>;
  _source?: 'found_by_id' | 'placeholder' | 'error' | 'offline_mock' | 'mock_data' | 'error_fallback_mock'; // Source of the comic data
}

// Simple mock data
const mockComics: Comic[] = [
  {
    id: 1,
    title: 'The Amazing Spider-Man',
    issueNumber: '1',
    description: 'The start of a new era for the wall-crawler as he faces off against a mysterious new foe known only as Kindred!',
    coverImageUrl: 'https://placehold.co/400x600/ef4444/ffffff?text=ASM+%231',
    releaseDate: '2024-01-15',
    creators: { writer: ['Nick Spencer'], artist: ['Ryan Ottley'] },
    featuredCharacters: [{ id: 620, name: 'Spider-Man' }],
    genres: ['Superhero', 'Action', 'Adventure']
  },
  {
    id: 2,
    title: 'Batman: City of Bane',
    issueNumber: '80',
    description: 'The final showdown between Batman and Bane! Gotham City has become Bane\'s city, but the Dark Knight returns to take it back.',
    coverImageUrl: 'https://placehold.co/400x600/3b82f6/ffffff?text=Batman+%2380',
    releaseDate: '2023-12-10',
    creators: { writer: ['Tom King'], artist: ['Mikel Janin'] },
    featuredCharacters: [{ id: 70, name: 'Batman' }, { id: 63, name: 'Bane' }],
  },
  {
    id: 3,
    title: 'X-Men: House of X',
    issueNumber: '1',
    description: 'Professor X reveals his master plan for mutantkind—one that will bring mutants out of the shadow of mankind and into the light.',
    coverImageUrl: 'https://placehold.co/400x600/10b981/ffffff?text=HoX+%231',
    releaseDate: '2024-02-20',
    creators: { writer: ['Jonathan Hickman'], artist: ['Pepe Larraz'] },
    featuredCharacters: [{ id: 717, name: 'Wolverine' }, { id: 196, name: 'Cyclops' }, { id: 526, name: 'Professor X' }],
  },
  {
    id: 4,
    title: 'Wonder Woman: Dead Earth',
    issueNumber: '1',
    description: 'Princess Diana of Themyscira awakens in a ravaged Earth to find humanity on the brink of extinction. She must unravel the mystery of what happened.',
    coverImageUrl: 'https://placehold.co/400x600/f59e0b/ffffff?text=WW+DE+%231',
    releaseDate: '2023-11-05',
    creators: { writer: ['Daniel Warren Johnson'], artist: ['Daniel Warren Johnson'] },
    featuredCharacters: [{ id: 720, name: 'Wonder Woman' }],
  },
   {
    id: 5,
    title: 'The Invincible Iron Man',
    issueNumber: '1',
    description: 'Tony Stark has lost it all: his company, his money, his friends. But he still has his armor, and a mystery to solve.',
    coverImageUrl: 'https://placehold.co/400x600/f87171/ffffff?text=Iron+Man+%231',
    releaseDate: '2024-03-01',
    creators: { writer: ['Gerry Duggan'], artist: ['Juan Frigeri'] },
    featuredCharacters: [{ id: 346, name: 'Iron Man' }],
  },
  {
    id: 6,
    title: 'Action Comics',
    issueNumber: '1050',
    description: 'A new era begins for the Man of Steel following his return from Warworld. What comes next for Superman and the Super-Family?',
    coverImageUrl: 'https://placehold.co/400x600/60a5fa/ffffff?text=AC+%231050',
    releaseDate: '2023-10-18',
    creators: { writer: ['Phillip Kennedy Johnson'], artist: ['Mike Perkins'] },
    featuredCharacters: [{ id: 644, name: 'Superman' }],
  },
  {
    id: 7,
    title: 'Daredevil: Born Again',
    issueNumber: '1',
    description: 'Matt Murdock returns to Hell\'s Kitchen after a long absence, but the shadows of his past still haunt him.',
    coverImageUrl: 'https://placehold.co/400x600/dc2626/ffffff?text=DD+%231',
    releaseDate: '2024-04-05',
    creators: { writer: ['Chip Zdarsky'], artist: ['Marco Checchetto'] },
    featuredCharacters: [{ id: 201, name: 'Daredevil' }],
  },
  {
    id: 8,
    title: 'Immortal Hulk',
    issueNumber: '50',
    description: 'The explosive finale to the critically acclaimed horror-infused Hulk saga.',
    coverImageUrl: 'https://placehold.co/400x600/16a34a/ffffff?text=Hulk+%2350',
    releaseDate: '2023-09-15',
    creators: { writer: ['Al Ewing'], artist: ['Joe Bennett'] },
    featuredCharacters: [{ id: 332, name: 'Hulk' }],
  },
  {
    id: 9,
    title: 'Thor: God of Thunder',
    issueNumber: '1',
    description: 'Thor confronts a galactic god-killer known as Gorr the God-Butcher across time and space.',
    coverImageUrl: 'https://placehold.co/400x600/0ea5e9/ffffff?text=Thor+%231',
    releaseDate: '2024-01-20',
    creators: { writer: ['Jason Aaron'], artist: ['Esad Ribic'] },
    featuredCharacters: [{ id: 659, name: 'Thor' }],
  },
  {
    id: 10,
    title: 'Justice League: Last Ride',
    issueNumber: '1',
    description: 'A disbanded Justice League must reunite to protect a dangerous prisoner on a remote world.',
    coverImageUrl: 'https://placehold.co/400x600/818cf8/ffffff?text=JL+%231',
    releaseDate: '2024-02-11',
    creators: { writer: ['Chip Zdarsky'], artist: ['Miguel Mendonça'] },
    featuredCharacters: [{ id: 70, name: 'Batman' }, { id: 644, name: 'Superman' }, { id: 720, name: 'Wonder Woman' }],
  },
  {
    id: 11,
    title: 'Venom',
    issueNumber: '200',
    description: 'Eddie Brock and the Venom symbiote face off against Knull, the God of the Symbiotes.',
    coverImageUrl: 'https://placehold.co/400x600/27272a/ffffff?text=Venom+%23200',
    releaseDate: '2023-11-28',
    creators: { writer: ['Donny Cates'], artist: ['Ryan Stegman'] },
    featuredCharacters: [{ id: 687, name: 'Venom' }],
  },
  {
    id: 12,
    title: 'Captain America: Sentinel of Liberty',
    issueNumber: '1',
    description: 'Steve Rogers returns to his roots when a mysterious conspiracy targets the symbol of America.',
    coverImageUrl: 'https://placehold.co/400x600/2563eb/ffffff?text=Cap+%231',
    releaseDate: '2024-03-15',
    creators: { writer: ['Jackson Lanzing', 'Collin Kelly'], artist: ['Carmen Carnero'] },
    featuredCharacters: [{ id: 149, name: 'Captain America' }],
  },
  {
    id: 13,
    title: 'Flash: Fastest Man Alive',
    issueNumber: '768',
    description: 'Barry Allen discovers the true source of the Speed Force and what it means for speedsters everywhere.',
    coverImageUrl: 'https://placehold.co/400x600/dc2626/ffffff?text=Flash+%23768',
    releaseDate: '2023-12-05',
    creators: { writer: ['Jeremy Adams'], artist: ['Brandon Peterson'] },
    featuredCharacters: [{ id: 263, name: 'The Flash' }],
  },
  {
    id: 14,
    title: 'Black Panther: The Intergalactic Empire',
    issueNumber: '1',
    description: 'T\'Challa must balance his duties to Wakanda and the new Intergalactic Empire of Wakanda.',
    coverImageUrl: 'https://placehold.co/400x600/1e293b/ffffff?text=BP+%231',
    releaseDate: '2024-05-10',
    creators: { writer: ['Eve L. Ewing'], artist: ['Chris Allen'] },
    featuredCharacters: [{ id: 106, name: 'Black Panther' }],
  },
  {
    id: 15,
    title: 'Aquaman: The Becoming',
    issueNumber: '1',
    description: 'A new threat from the depths forces Arthur Curry to confront his dual heritage.',
    coverImageUrl: 'https://placehold.co/400x600/0891b2/ffffff?text=Aquaman+%231',
    releaseDate: '2023-10-30',
    creators: { writer: ['Brandon Thomas'], artist: ['Diego Olortegui'] },
    featuredCharacters: [{ id: 50, name: 'Aquaman' }],
  },
  {
    id: 16,
    title: 'Ms. Marvel: Generation Why',
    issueNumber: '1',
    description: 'Kamala Khan juggles being a teenager, an Avenger, and Jersey City\'s protector.',
    coverImageUrl: 'https://placehold.co/400x600/be185d/ffffff?text=Ms+Marvel+%231',
    releaseDate: '2024-04-22',
    creators: { writer: ['Saladin Ahmed'], artist: ['Minkyu Jung'] },
    featuredCharacters: [{ id: 156, name: 'Ms. Marvel' }],
  },
  {
    id: 17,
    title: 'Green Lantern: Far Sector',
    issueNumber: '1',
    description: 'Rookie Green Lantern Sojourner "Jo" Mullein investigates a murder in a city where emotions are forbidden.',
    coverImageUrl: 'https://placehold.co/400x600/15803d/ffffff?text=GL+%231',
    releaseDate: '2023-08-05',
    creators: { writer: ['N.K. Jemisin'], artist: ['Jamal Campbell'] },
    featuredCharacters: [{ id: 304, name: 'Green Lantern' }],
  },
  {
    id: 18,
    title: 'Fantastic Four: First Family',
    issueNumber: '1',
    description: 'Reed, Sue, Johnny, and Ben face a cosmic threat that dates back to the earliest days of their powers.',
    coverImageUrl: 'https://placehold.co/400x600/2563eb/ffffff?text=FF+%231',
    releaseDate: '2024-06-01',
    creators: { writer: ['Ryan North'], artist: ['Iban Coello'] },
    featuredCharacters: [{ id: 251, name: 'Mr. Fantastic' }, { id: 558, name: 'Invisible Woman' }, { id: 341, name: 'Human Torch' }, { id: 106, name: 'The Thing' }],
  },
  {
    id: 19,
    title: 'Harley Quinn: Rogue\'s Gallery',
    issueNumber: '25',
    description: 'Harley Quinn takes on Batman\'s most dangerous villains in a chaotic battle for Gotham.',
    coverImageUrl: 'https://placehold.co/400x600/ec4899/ffffff?text=Harley+%2325',
    releaseDate: '2023-11-15',
    creators: { writer: ['Stephanie Phillips'], artist: ['Riley Rossmo'] },
    featuredCharacters: [{ id: 309, name: 'Harley Quinn' }],
  },
  {
    id: 20,
    title: 'Doctor Strange: Sorcerer Supreme',
    issueNumber: '1',
    description: 'Stephen Strange confronts a mystical plague that threatens the fabric of reality itself.',
    coverImageUrl: 'https://placehold.co/400x600/7e22ce/ffffff?text=Strange+%231',
    releaseDate: '2024-02-28',
    creators: { writer: ['Jed MacKay'], artist: ['Pasqual Ferry'] },
    featuredCharacters: [{ id: 226, name: 'Doctor Strange' }],
  },
  {
    id: 21,
    title: 'Moon Knight: Midnight Mission',
    issueNumber: '1',
    description: 'Marc Spector opens a midnight mission to protect those who travel at night.',
    coverImageUrl: 'https://placehold.co/400x600/f5f5f4/0e0e0e?text=Moon+Knight+%231',
    releaseDate: '2023-09-20',
    creators: { writer: ['Jed MacKay'], artist: ['Alessandro Cappuccio'] },
    featuredCharacters: [{ id: 432, name: 'Moon Knight' }],
  },
  {
    id: 22,
    title: 'Nightwing: Leaping Into The Light',
    issueNumber: '78',
    description: 'Dick Grayson returns to Blüdhaven and faces a new threat to the city.',
    coverImageUrl: 'https://placehold.co/400x600/1e40af/ffffff?text=Nightwing+%2378',
    releaseDate: '2024-01-05',
    creators: { writer: ['Tom Taylor'], artist: ['Bruno Redondo'] },
    featuredCharacters: [{ id: 461, name: 'Nightwing' }],
  },
  {
    id: 23,
    title: 'She-Hulk: Law and Disorder',
    issueNumber: '1',
    description: 'Jennifer Walters balances superheroics with her legal career in this new series.',
    coverImageUrl: 'https://placehold.co/400x600/22c55e/ffffff?text=She-Hulk+%231',
    releaseDate: '2024-05-15',
    creators: { writer: ['Rainbow Rowell'], artist: ['Rogerso Moura'] },
    featuredCharacters: [{ id: 603, name: 'She-Hulk' }],
  },
  {
    id: 24,
    title: 'Shazam: Power of Hope',
    issueNumber: '1',
    description: 'Billy Batson must relearn what it means to be a hero when his powers begin to change.',
    coverImageUrl: 'https://placehold.co/400x600/ea580c/ffffff?text=Shazam+%231',
    releaseDate: '2023-12-25',
    creators: { writer: ['Gene Luen Yang'], artist: ['Dan Mora'] },
    featuredCharacters: [{ id: 602, name: 'Shazam' }],
  },
];

export default mockComics; 